"""Add recurring event fields

Revision ID: 3efa235d6c88
Revises: 
Create Date: 2024-10-13 11:22:59.849833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3efa235d6c88'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_recurring', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('recurrence_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('recurrence_end_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('recurrence_end_date')
        batch_op.drop_column('recurrence_type')
        batch_op.drop_column('is_recurring')

    # ### end Alembic commands ###
