"""Add custom_recurrence_dates to Event model

Revision ID: 99526a9642e7
Revises: 3efa235d6c88
Create Date: 2024-10-13 11:31:38.548141

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '99526a9642e7'
down_revision = '3efa235d6c88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_recurrence_dates', postgresql.ARRAY(sa.Date()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('custom_recurrence_dates')

    # ### end Alembic commands ###
